Automatically assign roles from #request-rank
LPD-VRChat/LPD-Officer-Monitor pull request #59
Opened 2021-04-22 01:25 UTC by CaptainDestructo

Smaller items first:

- Moved `all_lpd_ranks` definition to the loop in Officer Manager, that way if for some reason the hierarchy is updated in Discord, it will be updated in the bot on the next loop. --- Added `Tuple(bot.officer_manager.all_lpd_ranks)` to available variables.
- Added `Offier.rank` property, which returns the Officer's `Discord.Role` object having the highest position in the role hierarchy that also appears in `self.bot.officer_manager.all_lpd_ranks`.

Now for the main event:

When a message is sent in the `#request-rank` channel as specified in the settings file, process the message.

Messages will be processed under the following conditions:

- Message must be sent by an LPD cadet or officer (verified by presence of Officer object)
- Message must contain at least one mention
- Message must contain case-insensitive substrings `'trained by'` and `'request rank'`

If processing proceeds, the bot will react to the message with a ✅ for the one of the mentioned trainers to click within the specified timeout (default 300 seconds).

The bot will iterate through an internally defined dictionary of requestable roles, and select the first one where the role name appears in the message. This will cause unknown behavior if multiple roles are specified. Theoretically, it would process as if the first role in the internal dictionary were found.

During processing, the bot will check the position of the user's current LPD rank role against the position of the `prereq` role in the dictionary, as well as the `upgrade` boolean to determine whether or not the user has the correct rank to request that particular role. 

> If the test fails, the user's message will be deleted, they will be notified that they have insufficient rank, and the function will return without assigning or removing roles.

The bot will then gather a list of Officer IDs which are allowed to approve the request. This list contains the IDs of mentioned users having the specified `approver` role. When one of those officers clicks the ✅ within the timeout period, the bot will assign the user the requested role, and then delete the `prereq` role if `upgrade` is True.

> After an allowed approver clicks the ✅ and roles are assigned/removed, or the timeout period expires, whichever comes first, the function will return.

If the function has not returned after iterating through the dictionary, it means that a non-standard rank was requested. In this case, the bot will react with a ❓, and the function will return.

Other processing functions in this bot would usually delete the message and notify the user that there is a problem, however in this case I have opted to include forward compatibility for future ranks. If ranks are added, Staff will still be able to manually approve requests until the rank is added to the internal dictionary.

2021-04-24 01:05 UTC, hrolfurgylfa requested changes
Except for these few things, the code looked really good, and these were really minor anyway. I haven't gotten the time to try running it yet though, I will go ahead and try that sometime tomorrow.

2021-04-24 01:05 UTC, hrolfurgylfa commented on Classes/extra_functions.py
> +            # current_rank = list(set(message.author.roles) & set(bot.officer_manager.all_lpd_ranks))[0]
Sorry, this was only supposed to reference line 280

2021-04-24 02:36 UTC, CaptainDestructo commented on Classes/extra_functions.py
> +            # current_rank = list(set(message.author.roles) & set(bot.officer_manager.all_lpd_ranks))[0]
Removed line 280

2021-04-24 02:39 UTC, CaptainDestructo commented on Classes/extra_functions.py
> +    )
I wasn't aware black had this feature. I disabled formatting for this section.

2021-04-24 02:39 UTC, CaptainDestructo commented on Classes/commands.py
> +                pattern = re.compile(r"(LPD )?(\w+( \w+)*)")
Moved to top of command outside loop

2021-04-26 17:41 UTC, hrolfurgylfa approved these changes
Seems good to me

2021-04-26 17:41 UTC, merged