Renewal time sql table fix
LPD-VRChat/LPD-Officer-Monitor pull request #76
Opened 2021-06-08 22:44 UTC by hrolfurgylfa

This fixes the OfficerManager.get_officer_renew_dates function to use renewal time in a seperate table and also adds the table used into the database.sql file. This is the SQL table used:
```mysql
CREATE TABLE RenewalTimes
(
    renewal_id INT PRIMARY KEY AUTO_INCREMENT,
    officer_id BIGINT UNSIGNED,
    renewed_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    renewed_by BIGINT UNSIGNED,
    reason TEXT,

    CONSTRAINT officer_id_FK_RT FOREIGN KEY (officer_id) REFERENCES Officers(officer_id),
    CONSTRAINT renewed_by_FK FOREIGN KEY (renewed_by) REFERENCES Officers(officer_id)
);
```

2021-06-08 22:49 UTC, CaptainDestructo commented
The only problem I see here is the foreign constraint with the renewed_by column. We’ll need to add a SQL call in remove_office to delete renewal entries an officer has made if they leave. 

It may be best to remove that constraint, so that if a staff member leaves, any officers whose time they renewed will still have it.

2021-06-08 22:53 UTC, hrolfurgylfa commented
@CaptainDestructo When something like this references an officer it should really be a forign key though. We should rather add another thing to drop it or just CASCADE DROP the officer, so that all their records go with them.

2021-06-08 22:56 UTC, CaptainDestructo commented
I would agree with you, however this would cause officers to lose their renewed status if that staff member left. Is that what we want to happen?

I’m ok with changing Officers to a cascade drop, we just need to make sure we all use the same SQL

2021-06-08 22:58 UTC, hrolfurgylfa commented
Yeah, we should be able to have it optional but still a forign key, I can check it tomorrow.

2021-06-09 00:18 UTC, CaptainDestructo requested changes
Change renewed_by foreign key to a non-constraining type.
Also consider CASCADE DROP on Officers table. That will eliminate the need for all the DELETE FROM statements in OfficerManager.remove_officer()

2021-06-12 20:22 UTC, CaptainDestructo approved these changes
These changes will require additional SQL to be run for existing tables to update the foreign keys.

2021-06-12 20:23 UTC, merged